###
# This single workflow file combines two jobs:
# 1. Generating a snake animation of your GitHub contributions.
# 2. Generating a 3D visualization of your GitHub contributions.
#
# Both jobs are triggered by the same events: a daily schedule, a push to `main`,
# and a manual trigger via `workflow_dispatch`.
###
name: GitHub Profile Workflows

# Define the triggers for the entire workflow.
on:
  # The workflow executes every day at 18:00 UTC (03:00 JST).
  schedule:
    - cron: "0 18 * * *"
  # This allows for manual triggering from the GitHub UI.
  workflow_dispatch:
  # The workflow also runs on pushes to the `main` branch.
  push:
    branches:
      - main

# The `permissions` are applied to all jobs in this workflow.
permissions:
  contents: write

jobs:
  # Job 1: Generates the snake animation.
  generate-snake:
    name: Generate snake animation
    runs-on: ubuntu-latest
    # A timeout to prevent the job from running too long.
    timeout-minutes: 5

    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          # Your GitHub username is used automatically.
          github_user_name: ${{ github.repository_owner }}
          # The output file path and palette for the generated SVG.
          outputs: dist/snake.svg?palette=github-dark

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # The target branch for the output file. This branch must exist.
          target_branch: output
          # The directory containing the file to be pushed.
          build_dir: dist
        env:
          # The GITHUB_TOKEN is automatically provided.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Job 2: Generates the 3D contributions visualization.
  generate-3d-contrib:
    name: Generate 3D contributions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          # The GITHUB_TOKEN is automatically provided.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The username for the contributions data.
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          # Commits only if there are changes to avoid empty commits.
          if git commit -m "generated 3D contrib"; then
            git push
          fi
